"""address model fix

Revision ID: 0bce0147bd67
Revises: 3848c4768572
Create Date: 2022-05-03 19:28:48.721892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bce0147bd67'
down_revision = '3848c4768572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
