"""nullable image url

Revision ID: 1dc4540f1613
Revises: 6e4391a463a7
Create Date: 2022-05-08 01:52:55.072339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc4540f1613'
down_revision = '6e4391a463a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subcategory', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcategory', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
