"""phonenumber and personal name is added

Revision ID: 1e1c88035621
Revises: 51b32a8d6b7c
Create Date: 2022-05-05 21:04:58.094297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1c88035621'
down_revision = '51b32a8d6b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('personal_name', sa.String(length=100), nullable=False))
    op.add_column('address', sa.Column('phone_number', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'phone_number')
    op.drop_column('address', 'personal_name')
    # ### end Alembic commands ###
