"""categories many to many

Revision ID: 22ef32d70ecf
Revises: b8eb59a178cb
Create Date: 2022-04-24 14:42:11.482871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ef32d70ecf'
down_revision = 'b8eb59a178cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_subcategory_id'), 'category_subcategory', ['id'], unique=False)
    op.add_column('product', sa.Column('category_subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category_subcategory', ['category_subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_subcategory_id')
    op.drop_index(op.f('ix_category_subcategory_id'), table_name='category_subcategory')
    op.drop_table('category_subcategory')
    op.drop_table('subcategory')
    op.drop_table('category')
    # ### end Alembic commands ###
