"""nullable true for credit model for fixing error in server

Revision ID: 2694d5ecd973
Revises: 74c58ceb7d0b
Create Date: 2022-06-02 11:32:16.178119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2694d5ecd973"
down_revision = "74c58ceb7d0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit", "payment_method", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "credit", "card_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("credit", "cardnumber", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("credit", "CW", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column(
        "credit", "expiry_date", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit", "expiry_date", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "credit", "CW", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column("credit", "cardnumber", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "credit", "card_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "credit", "payment_method", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
