"""proxies

Revision ID: 378143edade0
Revises: 22ef32d70ecf
Create Date: 2022-04-24 16:11:24.619452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378143edade0'
down_revision = '22ef32d70ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
