"""address_table_v1

Revision ID: 3848c4768572
Revises: 7e3ea650bdfa
Create Date: 2022-05-03 17:25:08.555305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3848c4768572'
down_revision = '7e3ea650bdfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('card_number', sa.String(length=100), nullable=False),
    sa.Column('CW', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
