"""removed char limit for card number

Revision ID: 3967e6bb525d
Revises: 68d30c47d9c3
Create Date: 2022-05-31 22:53:22.343603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3967e6bb525d'
down_revision = '68d30c47d9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('cardnumber', sa.String(), nullable=False))
    op.drop_column('credit', 'card_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('card_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('credit', 'cardnumber')
    # ### end Alembic commands ###
