"""shopping cart fix

Revision ID: 4cb26896f32f
Revises: 7a42c7196af2
Create Date: 2022-05-07 07:41:08.212743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb26896f32f'
down_revision = '7a42c7196af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_shopping_cart_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'shopping_cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('shopping_cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_shopping_cart_id_fkey', 'user', 'shoppingcart', ['shopping_cart_id'], ['id'])
    # ### end Alembic commands ###
