"""address_table_v2

Revision ID: 51b32a8d6b7c
Revises: 9475bc120d97
Create Date: 2022-05-04 11:39:57.129150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b32a8d6b7c'
down_revision = '9475bc120d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
