"""discount-field

Revision ID: 5248e44b2823
Revises: 2694d5ecd973
Create Date: 2022-06-02 12:58:14.264153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5248e44b2823'
down_revision = '2694d5ecd973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Integer(), nullable=True))
    op.alter_column('user', 'user_type',
               existing_type=postgresql.ENUM('CUSTOMER', 'SALES_MANAGER', 'PRODUCT_MANAGER', name='usertype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=postgresql.ENUM('CUSTOMER', 'SALES_MANAGER', 'PRODUCT_MANAGER', name='usertype'),
               nullable=False)
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
