"""distributor added

Revision ID: 64eff57b1463
Revises: 1e1c88035621
Create Date: 2022-05-06 13:30:04.395218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eff57b1463'
down_revision = '1e1c88035621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('distributor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'distributor')
    # ### end Alembic commands ###
