"""is active comment field

Revision ID: 68d30c47d9c3
Revises: 76ea4f86b93a
Create Date: 2022-05-09 00:09:42.446116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d30c47d9c3'
down_revision = '76ea4f86b93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_active')
    # ### end Alembic commands ###
