"""comment rate

Revision ID: 76ea4f86b93a
Revises: cda0f86eb617
Create Date: 2022-05-08 11:20:55.123744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ea4f86b93a'
down_revision = 'cda0f86eb617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'rate')
    # ### end Alembic commands ###
