"""shopping cart

Revision ID: 7a42c7196af2
Revises: e9842be92824
Create Date: 2022-05-07 07:17:16.618874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a42c7196af2'
down_revision = 'e9842be92824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppingcart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shoppingcart_id'), 'shoppingcart', ['id'], unique=False)
    op.add_column('user', sa.Column('shopping_cart_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'shoppingcart', ['shopping_cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'shopping_cart_id')
    op.drop_index(op.f('ix_shoppingcart_id'), table_name='shoppingcart')
    op.drop_table('shoppingcart')
    # ### end Alembic commands ###
