"""category photo field is added

Revision ID: 7e3ea650bdfa
Revises: 378143edade0
Create Date: 2022-05-02 22:40:21.246906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3ea650bdfa'
down_revision = '378143edade0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image_url')
    # ### end Alembic commands ###
