"""address model fields are changed

Revision ID: 845a9e0a76e1
Revises: 0bce0147bd67
Create Date: 2022-05-04 00:48:03.817888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845a9e0a76e1'
down_revision = '0bce0147bd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('address', sa.Column('full_address', sa.String(length=100), nullable=False))
    op.add_column('address', sa.Column('postal_code', sa.String(length=100), nullable=False))
    op.add_column('address', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('address', sa.Column('province', sa.String(length=100), nullable=False))
    op.add_column('address', sa.Column('country', sa.String(length=100), nullable=False))
    op.drop_column('address', 'card_name')
    op.drop_column('address', 'expiry_date')
    op.drop_column('address', 'card_number')
    op.drop_column('address', 'CW')
    op.drop_column('address', 'payment_method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('payment_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('CW', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('card_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('expiry_date', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('card_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('address', 'country')
    op.drop_column('address', 'province')
    op.drop_column('address', 'city')
    op.drop_column('address', 'postal_code')
    op.drop_column('address', 'full_address')
    op.drop_column('address', 'name')
    # ### end Alembic commands ###
