"""credit_table_v1

Revision ID: 9475bc120d97
Revises: d284a6bb436a
Create Date: 2022-05-04 11:04:43.302896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9475bc120d97'
down_revision = 'd284a6bb436a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('card_number', sa.String(length=100), nullable=False),
    sa.Column('CW', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit')
    # ### end Alembic commands ###
