"""product column is added, relation with comment and product is done

Revision ID: b8eb59a178cb
Revises: f64a0cc926af
Create Date: 2022-04-17 22:45:58.922989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8eb59a178cb'
down_revision = 'f64a0cc926af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.add_column('comment', sa.Column('content', sa.String(length=1000), nullable=False))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('comment', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_comment_id', table_name='comment')
    op.create_foreign_key(None, 'comment', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_column('comment', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_index('ix_comment_id', 'comment', ['id'], unique=False)
    op.alter_column('comment', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'content')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
