"""relation fix on product

Revision ID: cd89dc26c234
Revises: 1e1c88035621
Create Date: 2022-05-06 13:12:38.986396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd89dc26c234'
down_revision = '1e1c88035621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
