"""category order id nullable fix

Revision ID: cda0f86eb617
Revises: f515f6687d32
Create Date: 2022-05-08 03:05:17.264306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cda0f86eb617"
down_revision = "f515f6687d32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subcategory", "order_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subcategory", "order_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
