"""product fields are added

Revision ID: d284a6bb436a
Revises: 96ab95e5dbc3
Create Date: 2022-05-04 04:19:11.204765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd284a6bb436a'
down_revision = '96ab95e5dbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('title', sa.String(length=125), nullable=False))
    op.add_column('product', sa.Column('description', sa.String(), nullable=False))
    op.add_column('product', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('model', sa.String(), nullable=True))
    op.add_column('product', sa.Column('number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'number')
    op.drop_column('product', 'model')
    op.drop_column('product', 'price')
    op.drop_column('product', 'stock')
    op.drop_column('product', 'description')
    op.drop_column('product', 'title')
    # ### end Alembic commands ###
