"""comments migration fix4

Revision ID: f326ded4f75e
Revises: e35723cf4a4b
Create Date: 2022-04-18 02:34:45.757556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f326ded4f75e'
down_revision = 'e35723cf4a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
